[package]
name = "goopho"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 3 # Run about as fast as 'release'.

[profile.release]
debug = 1

[dependencies]
async-trait = "0.1.73"
async-walkdir = "0.2.0"
clap = { version = "4.4.3", features = ["derive"] }
futures-lite = "1.13.0"
image = "0.24.7"
sqlx = { version = "0.7.1", features = ["runtime-tokio-rustls", "sqlite"] }
strum = { version = "0.25.0", features = ["derive"] }
time = "0.3.28"
tokio = { version = "1.32.0", features = ["macros", "rt-multi-thread", "signal"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
