[package]
name = "goopho"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-walkdir = "0.2.0"
futures-lite = "1.12.0"
image = "0.23"
imagesize = "0.11.0"
img_hash = "3.2.0"
tokio = { version = "1.25.0", features = ["macros", "rt-multi-thread"] }
